from . import db
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))
    role = db.Column(db.String(50))

class SMS1(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    h0 = db.Column(db.Float)
    q_in = db.Column(db.Float)
    Qout = db.Column(db.Float)
    t = db.Column(db.Float)
    inflow = db.Column(db.Float)
    elevasi_awal = db.Column(db.Float)
    elevasi_akhir = db.Column(db.Float)
    outflow_selorejo = db.Column(db.Float)
    daya_output_selorejo = db.Column(db.Float)
    energi_output_selorejo = db.Column(db.Float)
    inflow_mendalan = db.Column(db.Float)
    daya_output_mendalan_1 = db.Column(db.Float)
    daya_output_mendalan_2 = db.Column(db.Float)
    daya_output_mendalan_3 = db.Column(db.Float)
    daya_output_mendalan_4 = db.Column(db.Float)
    total_daya_output_mendalan = db.Column(db.Float)
    energi_output_mendalan = db.Column(db.Float)
    suplesi = db.Column(db.Float)
    inflow_siman = db.Column(db.Float)
    daya_output_siman_1 = db.Column(db.Float)
    daya_output_siman_2 = db.Column(db.Float)
    daya_output_siman_3 = db.Column(db.Float)
    total_daya_output_siman = db.Column(db.Float)
    energi_output_siman = db.Column(db.Float)

class SMS2(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    h0 = db.Column(db.Float)
    ht = db.Column(db.Float)
    q_in = db.Column(db.Float)
    t = db.Column(db.Float)
    inflow = db.Column(db.Float)
    elevasi_awal = db.Column(db.Float)
    elevasi_akhir = db.Column(db.Float)
    outflow_selorejo = db.Column(db.Float)
    daya_output_selorejo = db.Column(db.Float)
    energi_output_selorejo = db.Column(db.Float)
    inflow_mendalan = db.Column(db.Float)
    daya_output_mendalan_1 = db.Column(db.Float)
    daya_output_mendalan_2 = db.Column(db.Float)
    daya_output_mendalan_3 = db.Column(db.Float)
    daya_output_mendalan_4 = db.Column(db.Float)
    total_daya_output_mendalan = db.Column(db.Float)
    energi_output_mendalan = db.Column(db.Float)
    suplesi = db.Column(db.Float)
    inflow_siman = db.Column(db.Float)
    daya_output_siman_1 = db.Column(db.Float)
    daya_output_siman_2 = db.Column(db.Float)
    daya_output_siman_3 = db.Column(db.Float)
    total_daya_output_siman = db.Column(db.Float)
    energi_output_siman = db.Column(db.Float)

class SutamiWlingi(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    elevasi_awal = db.Column(db.Float)
    elevasi_akhir = db.Column(db.Float)
    inflow = db.Column(db.Float)
    beban_wlingi = db.Column(db.Float)
    elevasi_real_wlingi = db.Column(db.Float)
    elevasi_target_wlingi = db.Column(db.Float)
    q_wlingi_yesterday = db.Column(db.Float)
    jam_mati_wlingi_kemarin = db.Column(db.Float)
    vol_tersedia = db.Column(db.Float)
    vol_used = db.Column(db.Float)
    volume_sisa = db.Column(db.Float)
    mean_beban_sutami_1 = db.Column(db.Float)
    mean_beban_sutami_2 = db.Column(db.Float)
    mean_beban_sutami_3 = db.Column(db.Float)
    sum_beban_sutami_1 = db.Column(db.Float)
    sum_beban_sutami_2 = db.Column(db.Float)
    sum_beban_sutami_3 = db.Column(db.Float)
    beban_total_sutami = db.Column(db.Float)
    beban_total_wlingi = db.Column(db.Float)
    jam_mulai_operasi_today = db.Column(db.Float)
    jam_mati_operasi_wlingi = db.Column(db.Float)
    waktu_operasi_wlingi = db.Column(db.Float)
    energi_cascade = db.Column(db.Float)

class Sengguruh(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    inflow_sengguruh = db.Column(db.Float)
    beban_1 = db.Column(db.Float)
    beban_2 = db.Column(db.Float)
    energi_1 = db.Column(db.Float)
    energi_2 = db.Column(db.Float)
    total_beban = db.Column(db.Float)
    total_energi = db.Column(db.Float)

class DataWadukSms(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    h = db.Column(db.Float)
    p = db.Column(db.Float)
    q = db.Column(db.Float)

class DataWadukSutami(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    h = db.Column(db.Float)
    p = db.Column(db.Float)
    q = db.Column(db.Float)

db.Index('sms_h_p', DataWadukSms.h, DataWadukSms.p, unique=True)
db.Index('sutami_h_p', DataWadukSutami.h, DataWadukSutami.p, unique=True)
