"""Add Data Waduk

Revision ID: 188616a9b6c1
Revises: 90821cd8db49
Create Date: 2021-02-04 20:18:02.783174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188616a9b6c1'
down_revision = '90821cd8db49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_wadukSMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('q', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_waduk_sutami',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('q', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_waduk_sutami')
    op.drop_table('data_wadukSMS')
    # ### end Alembic commands ###
