"""Rename Table

Revision ID: 3e53def25421
Revises: 188616a9b6c1
Create Date: 2021-02-04 20:20:31.607029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e53def25421'
down_revision = '188616a9b6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_waduk_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('q', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data_wadukSMS')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_wadukSMS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('h', sa.FLOAT(), nullable=True),
    sa.Column('p', sa.FLOAT(), nullable=True),
    sa.Column('q', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data_waduk_sms')
    # ### end Alembic commands ###
