"""Add Sutami, Wlingi, Sutami Operasi

Revision ID: 8dd3bf604083
Revises: 9bf8d3c01e1d
Create Date: 2021-03-20 14:42:14.308774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd3bf604083'
down_revision = '9bf8d3c01e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_waduk_sutami',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_waduk_sutami_operasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('q', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sutamioperasi_h_p', 'data_waduk_sutami_operasi', ['h', 'p'], unique=True)
    op.create_table('data_waduk_wlingi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_waduk_wlingi')
    op.drop_index('sutamioperasi_h_p', table_name='data_waduk_sutami_operasi')
    op.drop_table('data_waduk_sutami_operasi')
    op.drop_table('data_waduk_sutami')
    # ### end Alembic commands ###
