"""Add H, P as unique index

Revision ID: 8e60a421a587
Revises: 3e53def25421
Create Date: 2021-02-08 17:30:13.261951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e60a421a587'
down_revision = '3e53def25421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sms_h_p', 'data_waduk_sms', ['h', 'p'], unique=True)
    op.create_index('sutami_h_p', 'data_waduk_sutami', ['h', 'p'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sutami_h_p', table_name='data_waduk_sutami')
    op.drop_index('sms_h_p', table_name='data_waduk_sms')
    # ### end Alembic commands ###
