"""Add daya_output_selorejo to SMS1 & SMS2

Revision ID: 90821cd8db49
Revises: 9a35d11d8f12
Create Date: 2021-01-24 21:37:45.132094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90821cd8db49'
down_revision = '9a35d11d8f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sm_s1', sa.Column('daya_output_selorejo', sa.Float(), nullable=True))
    op.add_column('sm_s2', sa.Column('daya_output_selorejo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sm_s2', 'daya_output_selorejo')
    op.drop_column('sm_s1', 'daya_output_selorejo')
    # ### end Alembic commands ###
