"""Add elevasi_awal to SMS1 & SMS2

Revision ID: 9a35d11d8f12
Revises: a76ec95103e6
Create Date: 2021-01-24 21:31:58.998226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a35d11d8f12'
down_revision = 'a76ec95103e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sm_s1', sa.Column('elevasi_awal', sa.Float(), nullable=True))
    op.add_column('sm_s2', sa.Column('elevasi_awal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sm_s2', 'elevasi_awal')
    op.drop_column('sm_s1', 'elevasi_awal')
    # ### end Alembic commands ###
