"""Drop Old Sutami

Revision ID: 9bf8d3c01e1d
Revises: e4e227a9402b
Create Date: 2021-03-20 14:41:09.571760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf8d3c01e1d'
down_revision = 'e4e227a9402b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_waduk_sutami')
    op.drop_table('data_waduk_wlingi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_waduk_wlingi',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elevation', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_waduk_sutami',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('h', sa.FLOAT(), nullable=True),
    sa.Column('p', sa.FLOAT(), nullable=True),
    sa.Column('q', sa.FLOAT(), nullable=True),
    sa.Column('elevation', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
