"""Initial database

Revision ID: a76ec95103e6
Revises: 
Create Date: 2021-01-24 20:18:16.878837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76ec95103e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sengguruh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inflow_sengguruh', sa.Float(), nullable=True),
    sa.Column('beban_1', sa.Float(), nullable=True),
    sa.Column('beban_2', sa.Float(), nullable=True),
    sa.Column('energi_1', sa.Float(), nullable=True),
    sa.Column('energi_2', sa.Float(), nullable=True),
    sa.Column('total_beban', sa.Float(), nullable=True),
    sa.Column('total_energi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sm_s1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h0', sa.Float(), nullable=True),
    sa.Column('q_in', sa.Float(), nullable=True),
    sa.Column('Qout', sa.Float(), nullable=True),
    sa.Column('t', sa.Float(), nullable=True),
    sa.Column('inflow', sa.Float(), nullable=True),
    sa.Column('elevasi_akhir', sa.Float(), nullable=True),
    sa.Column('outflow_selorejo', sa.Float(), nullable=True),
    sa.Column('energi_output_selorejo', sa.Float(), nullable=True),
    sa.Column('inflow_mendalan', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_1', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_2', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_3', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_4', sa.Float(), nullable=True),
    sa.Column('total_daya_output_mendalan', sa.Float(), nullable=True),
    sa.Column('energi_output_mendalan', sa.Float(), nullable=True),
    sa.Column('suplesi', sa.Float(), nullable=True),
    sa.Column('inflow_siman', sa.Float(), nullable=True),
    sa.Column('daya_output_siman_1', sa.Float(), nullable=True),
    sa.Column('daya_output_siman_2', sa.Float(), nullable=True),
    sa.Column('daya_output_siman_3', sa.Float(), nullable=True),
    sa.Column('total_daya_output_siman', sa.Float(), nullable=True),
    sa.Column('energi_output_siman', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sm_s2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h0', sa.Float(), nullable=True),
    sa.Column('ht', sa.Float(), nullable=True),
    sa.Column('q_in', sa.Float(), nullable=True),
    sa.Column('t', sa.Float(), nullable=True),
    sa.Column('inflow', sa.Float(), nullable=True),
    sa.Column('elevasi_akhir', sa.Float(), nullable=True),
    sa.Column('outflow_selorejo', sa.Float(), nullable=True),
    sa.Column('energi_output_selorejo', sa.Float(), nullable=True),
    sa.Column('inflow_mendalan', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_1', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_2', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_3', sa.Float(), nullable=True),
    sa.Column('daya_output_mendalan_4', sa.Float(), nullable=True),
    sa.Column('total_daya_output_mendalan', sa.Float(), nullable=True),
    sa.Column('energi_output_mendalan', sa.Float(), nullable=True),
    sa.Column('suplesi', sa.Float(), nullable=True),
    sa.Column('inflow_siman', sa.Float(), nullable=True),
    sa.Column('daya_output_siman_1', sa.Float(), nullable=True),
    sa.Column('daya_output_siman_2', sa.Float(), nullable=True),
    sa.Column('daya_output_siman_3', sa.Float(), nullable=True),
    sa.Column('total_daya_output_siman', sa.Float(), nullable=True),
    sa.Column('energi_output_siman', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sutami_wlingi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elevasi_awal', sa.Float(), nullable=True),
    sa.Column('elevasi_akhir', sa.Float(), nullable=True),
    sa.Column('inflow', sa.Float(), nullable=True),
    sa.Column('beban_wlingi', sa.Float(), nullable=True),
    sa.Column('elevasi_real_wlingi', sa.Float(), nullable=True),
    sa.Column('elevasi_target_wlingi', sa.Float(), nullable=True),
    sa.Column('q_wlingi_yesterday', sa.Float(), nullable=True),
    sa.Column('jam_mati_wlingi_kemarin', sa.Float(), nullable=True),
    sa.Column('vol_tersedia', sa.Float(), nullable=True),
    sa.Column('vol_used', sa.Float(), nullable=True),
    sa.Column('volume_sisa', sa.Float(), nullable=True),
    sa.Column('mean_beban_sutami_1', sa.Float(), nullable=True),
    sa.Column('mean_beban_sutami_2', sa.Float(), nullable=True),
    sa.Column('mean_beban_sutami_3', sa.Float(), nullable=True),
    sa.Column('sum_beban_sutami_1', sa.Float(), nullable=True),
    sa.Column('sum_beban_sutami_2', sa.Float(), nullable=True),
    sa.Column('sum_beban_sutami_3', sa.Float(), nullable=True),
    sa.Column('beban_total_sutami', sa.Float(), nullable=True),
    sa.Column('beban_total_wlingi', sa.Float(), nullable=True),
    sa.Column('jam_mulai_operasi_today', sa.Float(), nullable=True),
    sa.Column('jam_mati_operasi_wlingi', sa.Float(), nullable=True),
    sa.Column('waktu_operasi_wlingi', sa.Float(), nullable=True),
    sa.Column('energi_cascade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('sutami_wlingi')
    op.drop_table('sm_s2')
    op.drop_table('sm_s1')
    op.drop_table('sengguruh')
    # ### end Alembic commands ###
